### ISSUE TITLE
Maybe it's easier to cooperate/use cpp-peglib or chpeg

### ISSUE THREAD

**Issue by mingodad** [rwxrob/pegn#1]
I'm actually coopearitng/using `cpp-peglib` https://github.com/yhirose/cpp-peglib and `chpeg` https://github.com/ChrisHixon/chpeg and I think that both of then can be used/customized to produce a `pegn` parser interpreter and a `playground` too (https://chrishixon.github.io/chpeg/playground/ and https://yhirose.github.io/cpp-peglib/ ).

Here https://github.com/rwxrob/pegn-spec/issues/15#issue-1284905091 I attached a `pegn` grammar usable by `cpp-peglib` and here it's https://github.com/ChrisHixon/chpeg/issues/20#issuecomment-1168398963 for `chpeg`.

Both projects `cpp-peglib` and `chpeg` welcome collaboration/ideas/improvements and I invite you and anyone interested on similar problems to join !

**Comment by rwxrob** [comment]
That looks like an excellent project that is solving different problems. The only thing in common is seeking to have a language-agnostic meta language, and I'm happy to see a lot of similar ideas to the syntax I've been using.

Unfortunately, there is just too much missing from that project for me to really get behind it. The method of capture is sub-optimal, I didn't see named captures within a given rule scope, and there is absolutely no sign anywhere of building out a large, reserved set of rule definitions with verbose human-friendly documentation for each reserved rule, potentially in multiple languages.
